package model

import "time"

// RotationEpoch represents a period when specific rotation order was active.
// When the user list changes, the current epoch is closed and a new one is created.
// This provides a full history of rotation changes.
type RotationEpoch struct {
	ID         string     `json:"id"`
	ScheduleID string     `json:"schedule_id"`
	Layer      string     `json:"layer"`      // "l1" or "l2"
	Groups     [][]string `json:"groups"`     // Rotation order: groups of user IDs, e.g. [["a","b"],["c"]]
	StartTime  time.Time  `json:"start_time"`
	EndTime    *time.Time `json:"end_time"`   // NULL = current epoch
	CreatedAt  time.Time  `json:"created_at"`
}

// OnCallSegment represents a continuous period when a user is on-call.
// Generated by the SegmentGenerator, not stored in DB.
type OnCallSegment struct {
	UserIDs   []string          `json:"user_ids"`
	Users     []*User           `json:"users,omitempty"`
	StartTime time.Time         `json:"start_time"`
	EndTime   time.Time         `json:"end_time"`
	Layer     string            `json:"layer"` // "l1", "l2", "override"
	Override  *ScheduleOverride `json:"override,omitempty"`
	IsForever bool              `json:"is_forever,omitempty"` // True if segment extends beyond lookahead horizon
}
